version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'panz3r'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    reviewers:
      - 'panz3r'
    ignore:
      - dependency-name: 'fs-extra'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
