version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'panz3r'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - 'panz3r'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    reviewers:
      - 'panz3r'
    groups:
      oclif:
        patterns:
          - '@oclif/*'
          - 'oclif'
        exclude-patterns:
          - '@oclif/prettier-config'
      eslint:
        patterns:
          - '@eslint/*'
          - 'eslint*'
          - '@oclif/prettier-config'
